services:
  postgres:
    image: postgres:15-alpine
    container_name: genomics-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: genomics
      POSTGRES_PASSWORD: genomics_dev_2024
      POSTGRES_DB: genomics_platform
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: